### ISSUE TITLE
Slimming the content of the repository

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#193]
In the attempt of stripping down the number of components, I suggest to:
- [ ] merge together `camCalib`, `dualCamCalib`, and `camCalibWithPose` @drdanz  ( https://github.com/robotology/icub-main/issues/607 ).
- [ ] move `canBusSniffer` _elsewhere_  ( https://github.com/robotology/icub-main/issues/608 ).
- [ ] deal with `joystickControl` and `joystickCheck`; [**`yarp`**](https://github.com/robotology/yarp) has a joypad device (see https://github.com/robotology/yarp/pull/1133, and  https://github.com/robotology/icub-main/issues/609 ).
- [x] remove `testStereoMatch` (#735).
- [x] get rid finally of all `gtk` based modules ( https://github.com/robotology/icub-main/issues/606 ).
- [x] move `usbCamera` (and other generic devices) in [**`yarp`**](https://github.com/robotology/yarp).
- [x] `lumaChroma` moved into [`robotology/segmentation`](https://github.com/robotology/segmentation/commit/4d8ded67910d48489a7b9955ae63306918892cc7).
- [x] include `icub-cluster` into `yarpmanager` (see https://github.com/robotology/yarp/issues/730)
- [x] use `yarprobotinterface` deployer and thus remove `simCartesianControl` (done via https://github.com/robotology/icub-main/commit/c70ddbe9ac45c16ad1bffbc81efb9d4f587044ef)
- [x] host robots configuration files within a dedicated repository, see #360. 
- [x] move `pf3d*` modules in [**`icub-basic-demos`**](https://github.com/robotology/icub-basic-demos), see #192.
- [x] move `robotInterface` in [**`yarp`**](https://github.com/robotology/yarp) and rename it as _yarprobotinterface_ to be consistent with other yarp binaries (see https://github.com/robotology/QA/issues/109).
- [x] get rid of `iCubInterface` (see https://github.com/robotology/icub-main/commit/c6038729c9a3401a2d047a20c756867c35692944).
- [x] move `iCubInterfaceGuiLib` and `iCubInterfaceGui` in [**`robotology-legacy`**](https://github.com/orgs/robotology-legacy), see #221.
- [x] get rid finally of the `robotMotorGui`, see https://github.com/robotology/icub-main/issues/220.
- [x] get rid finally of the `icubmod` library along with the `icubmoddev` binary, see https://github.com/robotology/QA/issues/68.

**Comment by lornat75** [comment]
About testStereoMatch, canBusSniffer and focusTool: these are not automatic tests but guis. I would see more as test tools or something like that.

I like the idea of moving stuff out of icub-main; but we need to:
1) discuss what should remain in icub-main, i.e. what is the content of this repository? and move everything else out
2) set-up a superbuild that allows us to perform automatic tests on a dashboard otherwise we end up missing many errors

**Comment by pattacini** [comment]
I was proposing `icub-tests` as just first thought. Is there any more suitable place for them? Don't know.

1. **"What is the content of icub-main?"** Well, very difficult to answer indeed. At time being the only guidelines I tried to follow were in the direction to move out _superseded_ modules, clearly _self-contained_ libraries, or _never/very rarely_ used components (in terms of applications we know about). Of course, we can brainstorm about the _mission_ of our beloved `icub-main`.
2. Fine with me.

**Comment by pattacini** [comment]
@drdanz what's the status of **gtk modules**?
Can we declare them finally banned?

**Comment by drdanz** [comment]
@pattacini I don't know...

* We should have a new qt firmware tool but I've never used it

Perhaps we should schedule a quick meeting on the topic?

By the way
* icub-cluster was included in yarpmanager
* We now have an sdl joypad device in YARP
* We are considering moving the usb camera (and perhaps check if we have other generic devices) in YARP

**Comment by pattacini** [comment]
Thank you @drdanz for the quick update.
I'll highlight above the further steps you outlined to keep track.

**Comment by marcoaccame** [comment]
Hi @drdanz and @pattacini, about the `We should have a new qt firmware tool but I've never used it `:
we have had *FirmwareUpdater* in devel since december 2016 and in master since june. It replaces the GTK-based *canLoader* and *ethLoader*. See https://github.com/robotology/QA/issues/240.

**Comment by pattacini** [comment]
Great @marcoaccame 
So, shall we get shot of GTK once and for good? 😄

**Comment by marcoaccame** [comment]
For what regards *canLoader* and *ethLoader*: yes we can.

See however issue https://github.com/robotology/icub-main/issues/473 which I have just created to help  P&M (production & maintenance ) dropping the use of *canLoader* from an internal procedure of theirs.

**Comment by traversaro** [comment]
Probably this is worth having its own issues, but there are several points of the documentation that should be updated:
* https://github.com/robotology/icub-main/blob/cd2028daac5afcddb220f3b6a7bfe6caa4abdf7b/src/libraries/icubmod/canBusSkin/CanBusSkin.cpp#L964
* https://github.com/robotology/icub-firmware-shared/search?utf8=%E2%9C%93&q=canLoader&type=
* https://github.com/robotology/icub-firmware-shared/search?utf8=%E2%9C%93&q=ethLoader&type=
* https://github.com/robotology/icub-firmware-build/search?utf8=%E2%9C%93&q=canLoader&type=
* https://github.com/robotology/icub-firmware-build/search?utf8=%E2%9C%93&q=ethLoader&type=
* https://github.com/robotology/icub-firmware/search?utf8=%E2%9C%93&q=ethLoader&type=
* https://github.com/drdanz/icub-firmware/search?utf8=%E2%9C%93&q=canLoader&type=
* http://wiki.icub.org/wiki/CanLoader
* http://wiki.icub.org/index.php?title=Special%3ASearch&profile=default&search=CanLoader&fulltext=Search
* http://wiki.icub.org/wiki/Firmware

cc @lornat75

**Comment by marcoaccame** [comment]
I had a look at the links. There are several cases, hence I write some comments in here as an help to do proper changes when we remove GTK and related GUIs. 

1. The `icub-main/src/tools/canLoader/canLoaderLib` and `icub-main/src/tools/ethLoader/ethLoaderLib` libraries will remain because they are used also by the new FirmwareUpdater.
2. Name of variables/type in C/C++ code: in most cases it is wrong to modify them because they refer to protocols of the canLoaderLib / ethLoaderLib.
3. Online prints, such as yWarning(),  telling a robot's user to check vs a particular FW version: I would change the string `canLoader` with `FW maintenance tools`. In this way the user can refer to the proper section of the wiki (see later point).
4. Comments in C/C++ code: we could do the same string substitution as in point 3 but I don't see it so important to do.
5. Documentation on wiki: there will be robots with GTK GUI (only) for a while, hence it is not correct to remove any canLoader/ethLoader section. Now the wiki already mentions the double possibility of 
 use of canLoader/ethLoader or FirmwareUpdater. What I would do is to edit the wiki to add a section *FW maintenance tools* where more focus is given to operations with FirmwareUpdater but which still contains references to canLoader+ethLoader.

**Comment by traversaro** [comment]
@pattacini for more fine-grained handling of this issue, I converted this issue in an epic and opened separate issues for each element left.
